DROP SHARE IF EXISTS RATINGS;
CREATE SHARE RATINGS;
GRANT USAGE ON DATABASE DATA_SHARING_RATINGS TO SHARE RATINGS;
USE DATABASE DATA_SHARING_RATINGS;
GRANT USAGE ON SCHEMA PRIVATE_SHARE TO SHARE RATINGS;
GRANT USAGE ON SCHEMA PUBLIC_SHARE TO SHARE RATINGS;
ALTER SHARE RATINGS ADD ACCOUNTS=PM2
