USE DATABASE DATA_SHARING_RATINGS;
DROP SCHEMA IF EXISTS MOVIE_LENS;
CREATE SCHEMA MOVIE_LENS COMMENT = 'Movie Lens test schema';
DROP SCHEMA IF EXISTS PRIVATE_SHARE;
CREATE SCHEMA PRIVATE_SHARE COMMENT = 'private data shared by provider';
DROP SCHEMA IF EXISTS PUBLIC_SHARE;
CREATE SCHEMA PUBLIC_SHARE COMMENT = 'public data shared by provider';
