DROP SHARE IF EXISTS MOVIE_LENS_RATINGS;
CREATE SHARE MOVIE_LENS_RATINGS;
GRANT USAGE ON DATABASE DATA_SHARING_RATINGS TO SHARE MOVIE_LENS_RATINGS;
USE DATABASE DATA_SHARING_RATINGS;
ALTER SHARE MOVIE_LENS_RATINGS ADD ACCOUNTS=PM2;
