USE DATABASE DATA_SHARING_RATINGS;
USE SCHEM MOVIE_LENS;

DROP TABLE IF EXISTS MOVIES;
CREATE TABLE MOVIES (
    MovieID INTEGER NOT NULL,
    Title STRING NOT NULL,
    Genres STRING NOT NULL);

DROP TABLE IF EXISTS PERMISSIONS;
CREATE TABLE PERMISSIONS (
    UserID INTEGER NOT NULL,
    AccountName STRING NOT NULL);

DROP TABLE IF EXISTS RATINGS
CREATE TABLE RATINGS (
    UserID INTEGER NOT NULL,
    MovieID INTEGER NOT NULL,
    Rating FLOAT NOT NULL,
    Timestamp Timestamp NOT NULL);
