USE DATABASE DATA_SHARING_RATINGS;
USE SCHEMA MOVIE_LENS;

DROP TABLE IF EXISTS MOVIE;
CREATE TABLE MOVIE (
    MovieID INTEGER NOT NULL,
    Title STRING NOT NULL,
    Genres STRING NOT NULL);

DROP TABLE IF EXISTS PERMISSION;
CREATE TABLE PERMISSION (
    RatingSourceID INTEGER NOT NULL,
    AccountName STRING NOT NULL);

DROP TABLE IF EXISTS RATING
CREATE TABLE RATING (
    RatingSourceID INTEGER NOT NULL,
    MovieID INTEGER NOT NULL,
    Rating FLOAT NOT NULL,
    Timestamp Timestamp NOT NULL);
