SELECT * FROM RATING_DETAILS;

SELECT 'PRIVATE',* FROM PRIVATE_SHARE.AVERAGE_RATINGS
WHERE TITLE = 'Beavis and Butt-Head Do America (1996)'
UNION
SELECT 'PUBLIC',* FROM PUBLIC_SHARE.AVERAGE_RATINGS
WHERE TITLE = 'Beavis and Butt-Head Do America (1996)'
