SELECT * FROM RATING_DETAILS;

SELECT 'PRIVATE',* FROM PRIVATE_SHARE.AVERAGE_RATINGS
WHERE TITLE = 'BEAVIS AND BUTT-HEAD DO AMERICA (1996)'
UNION
SELECT 'PUBLIC',* FROM PUBLIC_SHARE.AVERAGE_RATINGS
WHERE TITLE = 'BEAVIS AND BUTT-HEAD DO AMERICA (1996)'
